export const dataReg = {
    "Undang-Undang": [
      {
        id: 1,
        title: "Undang-Undang Dasar 1945 (Amandemen Keempat)",
        link: "https://drive.google.com/file/d/18RBupvbflP3eqGJ1x902CyoTXJCOAFVb/view",
        ket: "",
      },
      {
        id: 2,
        title: "Undang-Undang No. 33 Tahun 2009 tentang Perfilman",
        link: "https://drive.google.com/file/d/149RJwH6LGD3KLOWWI9HmMZP9hGvPxtfv/view",
        ket: "",
      },
      {
        id: 3,
        title: "Undang-Undang No. 36 Tahun 1999 tentang Telekomunikasi",
        link: "https://drive.google.com/file/d/1Def2PVL1HSPDBn7plcwfm2VR5Oj2mcwx/view",
        ket: "",
      },
      {
        id: 4,
        title: "Undang-Undang No. 40 Tahun 1999 tentang Pers",
        link: "https://drive.google.com/file/d/1I_Q65IfH5GKDTass65nKNIi1ftV-OceS/view",
        ket: "",
      },
      {
        id: 5,
        title: "Undang-Undang No. 19 Tahun 2002 tentang Hak Cipta",
        link: "https://drive.google.com/file/d/1sRFNdRmJjKTTjBtzme9p6RuwSPIBl_ku/view",
        ket: "",
      },
      {
        id: 6,
        title: "Undang-Undang No. 23 Tahun 2002 tentang Perlindungan Anak",
        link: "https://drive.google.com/file/d/1Ojk0bGVETT6y5FLhNQBRAldMIrrnJI53/view",
        ket: "",
      },
      {
        id: 7,
        title: "Undang-Undang No. 32 Tahun 2002 tentang Penyiaran",
        link: "https://drive.google.com/file/d/124K4OBBx0if_cVXy2HVGCZbjwnBcPHY5/view",
        ket: "",
      },
      {
        id: 8,
        title: "Undang-Undang No. 11 Tahun 2020 tentang Cipta Kerja",
        link: "https://drive.google.com/file/d/1dOPvQ3KKSt0k2odwb-WFsTNh5dqMGFFF/view",
        ket: "",
      }
    ],
    "Peraturan KPI": [
      {
        id: 1,
        title: "PKPI tahun 2023 Nomor 4",
        link: "https://drive.google.com/file/d/12NpMulHQe2DEO0MgTJm_i6a3UDDO5C9g/view",
        ket: "Tentang: Pengawasan Pemberitaan, Penyiaran dan Iklan Kampanye Pemilihan Umum Pada Lembaga Penyiaran",
      },
      {
        id: 2,
        title: "PKPI tahun 2023 Nomor 1",
        link: "https://drive.google.com/file/d/1dOPvQ3KKSt0k2odwb-WFsTNh5dqMGFFF/view",
        ket: "Tentang: Tata Cara Pengenaan Sanksi Administratif Terkait Isi Siaran",
      },
      {
        id: 3,
        title: "Rancangan PKPI tahun 2023",
        link: "https://drive.google.com/file/d/14kTTgtwBhTQaMVldyevIcrJ2ANuo6aQG/view",
        ket: "Tentang: Kelembagaan",
      },
      {
        id: 4,
        title: "PKPI tahun 2023 Nomor 2",
        link: "https://drive.google.com/file/d/1X4oB3wtDdqJrhKOPsKnyVD-0Jx3yycAL/view",
        ket: "Tentang: Rekomendasi Pencabutan Izin Penyelenggaraan Penyiaran Karena Tidak Melakukan Siaran",
      },
      {
        id: 5,
        title: "Instruksi Sekretaris KPI No. 01/P/KPI/2022",
        link: "https://drive.google.com/file/d/1e731C73WBx5dtZXyZ1N4rn9vrLUmUjWj/view",
        ket: "Tentang: Instruksi Sekretaris Komisi Penyiaran Indonesia Pusat Nomor I Tahun 2022 Tentang Penerapan Aplikasi Srikandi Di Lingkungan Komisi Penyiaran Indonesia Pusat",
      },
      {
        id: 6,
        title: "Peraturan KPI No. 01/P/KPI/2019_",
        link: "https://drive.google.com/file/d/1no6kHHNfPY2KDtoAXwXDJxe5bjzlfBJS/view",
        ket: "Tentang: Pedoman Tata Naskah Dinas Di Lingkungan Komisi Penyiaran Indonesia Pusat",
      },
      {
        id: 7,
        title: "Peraturan KPI No. 07/P/KPI/2020",
        link: "https://drive.google.com/file/d/1pcFgoLdINTZJvUoCz__h1Y7Xts7joxuk/view",
        ket: "Tentang: Pedoman Evaluasi Tahunan Persyaratan Program Siaran Lembaga Penyiaran Swasta",
      },
      {
        id: 8,
        title: "Pedoman KPI No. 01/P/KPI/2019",
        link: "https://drive.google.com/file/d/1z4pP9NpUVqQShQbgR08IZqiYUrWw7JLg/view",
        ket: "Tentang: Pengawasan dan Pemantauan Pemberitaan, Penyiaran, dan Iklan Kampanye Pemilihan Umum Tahun 2019 di Lembaga Penyiaran",
      },
      {
        id: 9,
        title: "Peraturan KPI No. 01/P/KPI/01/2019",
        link: "https://drive.google.com/file/d/17qKHMEHgV1JkmyKQObbVWIh_t1x9Hg_v/view",
        ket: "Tentang: Pemenuhan Komitmen Persyaratan Program Siaran Evaluasi Dengar Pendapat (EDP) dalam Online Single Submission Perizinan Penyelenggaraan Penyiaran",
      },
      {
        id: 10,
        title: "Peraturan KPI No. 05/P/KPI/05/2020  ",
        link: "https://drive.google.com/file/d/1JIgP6872pKKz7wuw6Q-kM7z9igAAwC0V/view",
        ket: "Tentang: Perhitungan Masa Jabatan Anggota Komisi Penyiaran Indonesia (KPI) Pengganti Antar Waktu Dalam Pemilihan Calon Anggota Komisi Penyiaran Indonesia Masa Jabatan Berikutnya",
      },
      {
        id: 11,
        title: "Peraturan KPI No. 01/P/KPI/07/2014",
        link: "https://kpi.go.id/download/regulasi/PKPI_01_P_KPI_07_2014.pdf",
        ket: "Tentang: Kelembagaan Komisi Penyiaran Indonesia",
      },
      {
        id: 12,
        title: "Keputusan KPI No. 45 Tahun 2014",
        link: "https://kpi.go.id/download/Keputusan_KPI/2014_45_KKPI_Petunjuk_Pelaksanaan_Pemilu.pdf",
        ket: "Tentang: Petunjuk Pelaksanaan Terkait Perlindungan Kepentingan Publik, Siaran Jurnalistik, Iklan, dan Pemilihan Umum",
      },
      {
        id: 13,
        title: "Pedoman Perilaku Penyiaran dan Standar Program Siaran (P3 & SPS)",
        link: "https://kpi.go.id/download/regulasi/P3SPS_2012_Final.pdf",
        ket: "Tentang: -",
      },
    ],
    "MoU": [
        {
            id: 1,
            title: "Nota Kesepahaman KPI dan BNN 2023",
            link: "https://drive.google.com/file/d/10yytxyiWJ4yXsBR_tfmNor28oZ8nUJB4/view",
            ket: "Tentang: Pencegahan dan Pemberantasan Penyalahgunaan dan Peredaran Gelap Narkotika dan Prekursor Narkotika",
        },
        {
            id: 2,
            title: "Keputusan Bersama antara BAWASLU, KPU, KPI dan Dewan Pers - 12 Agustus 2020 ",
            link: "https://drive.google.com/file/d/1mwARKZjY7p7BZTMRBGyRruT0fryYulxY/view",
            ket: "Tentang: Pengawasan dan Pemantauan Pemberitaan, Penyiaran, dan Iklan Kampanye dalam Pemilihan Gubernur dan Wakil Gubernur, Bupati dan Wakil Bupati, dan atau Wali Kota dan Wakil Wali Kota Tahun 2020, Melalui Lembaga Penyiaran, Perusahaan Pers Cetak, dan Siber",
        },
        {
            id: 3,
            title: "Keputusan Bersama antara BAWASLU, KPU, KPI dan KIP - 19 Mei 2014",
            link: "https://kpi.go.id/download/MoU/2014_Keputusan%20Bersama%20Bawaslu-KPU-KPI-KIP.pdf",
            ket: "Tentang: Pengawasan dan Pemantauan Pemberitaan, Penyiaran, dan Iklan Kampanye Pemilihan Umum Presiden dan Wakil Presiden Tahun 2014",
        },
        {
            id: 4,
            title: "Nota Kesepahaman antara KPI dan Dewan Pers - 22 April 2014",
            link: "https://kpi.go.id/download/MoU/2014_Nota%20Kesepahaman%20KPI%20dan%20Dewan%20Pers.pdf",
            ket: "Tentang: Penanganan Pelanggaran Isi Siaran Jurnalistik",
        },
        {
            id: 5,
            title: "Surat Keputusan Bersama BAWASLU, KPU, KPI dan KIP - 28 Februari 2014",
            link: "https://kpi.go.id/download/MoU/2014_SKB_4_Lembaga.pdf",
            ket: "Tentang: Kepatuhan Pada Ketentuan Pelaksanaan Kampanye Pemilihan Umum Melalui Media Penyiaran",
        },
        {
            id: 6,
            title: "Keputusan Bersama KPU, KPI dan Bawaslu - 18 Oktober 2013",
            link: "https://kpi.go.id/download/MoU/2013_Keputusan_Bersama_KPU_KPI_Bawaslu.pdf",
            ket: "Tentang: Pengawasan dan Pemantauan Pemberitaan, Penyiaran, dan Iklan Kampanye Pemilihan Umum Anggota Dewan Perwakilan Rakyat, Dewan Perwakilan Daerah, dan Dewan Perwakilan Rakyat Daerah",
        },
        {
            id: 7,
            title: "Nota Kesepahaman KPI dan KPU",
            link: "https://kpi.go.id/download/MoU/2012-01-31%20MoU%20KPI-KPU.pdf",
            ket: "Tentang: Pengaturan dan Pengawasan Pemberitaan, Penyiaran dan Iklan Kampanye Pemilihan Umum",
        },
        {
            id: 8,
            title: "Nota Kesepahaman KPI dan Persatuan Artis Musik Melayu-Dangdut Indonesia",
            link: "https://kpi.go.id/download/MoU/2012-03-29%20MoU%20KPI%20dan%20Persatuan%20Artis%20Musik%20Melayu-Dangdut%20Indonesia.pdf",
            ket: "Tentang: Penciptaan Penyiaran Yang Sehat Serta Mengurangi Dan Mencegah Program Siaran Musik Melayu-Dangdut Yang Bermuatan Seks Dan Pornografi",
        },
        {
            id: 9,
            title: "Nota Kesepahaman KPI dan BkkbN",
            link: "https://kpi.go.id/download/MoU/2012-04-1%20MoU%20KPI%20dan%20BkkbN.pdf",
            ket: "Tentang: Penciptaan Penyiaran Untuk Mendukung Program Kependudukan Dan Keluarga Berencana Dalam Mewujudkan Keluarga Kecil Bahagia Sejahtera",
        },
        {
            id: 10,
            title: "Nota Kesepahaman KPI dan Kepolisian Negara Republik Indonesia",
            link: "https://kpi.go.id/download/MoU/2012-09-12%20MoU%20KPI%20dan%20Kepolisian%20Negara%20Republik%20Indonesia.pdf",
            ket: "Tentang: Kerjasama Penyelenggaraan Penegakan Hukum Bantuan Teknis, Pendidikan Dan Latihan Di Bidang Penyiaran",
        },
        {
            id: 11,
            title: "Nota Kesepahaman KPI dan LSF",
            link: "https://kpi.go.id/download/MoU/2012-10-22%20MoU%20KPI%20dan%20LSF.pdf",
            ket: "Tentang: Penyensoran Dan Kewajiban Pencatuman Klasifikasi Usia Penonton Film Di Layar Televisi",
        },
        {
            id: 12,
            title: "Nota Kesepahaman KPI dan Lembaga Penyiaran Publlik Radio Republik Indonesia",
            link: "https://kpi.go.id/download/MoU/2012-12-11%20MoU%20KPI%20dan%20Lembaga%20Penyiaran%20Publik%20Radio%20Republik%20Indonesia.pdf",
            ket: "Tentang: Pendirian Dan Penyelenggaraan Penyiaran Lembaga Penyiaran Komunitas Di Wilayah Perbatasan Dan/Atau Daerah Tertinggal",
        },
    ],
  };
