export const dataBuku = [
    { id: 1, title: 'Kasus Silet: Kemenangan Bagi Publik', img: 'https://kpi.go.id/images/banners/Kasus_Silet.jpg' },
    { id: 2, title: 'Mata dan Telinga Pemirsa', img: 'https://kpi.go.id/images/banners/mata_telinga.jpg' },
    { id: 3, title: 'Demi Frekuensi Publik', img: 'https://kpi.go.id/images/banners/Demi_frekuensi.jpg' },
    { id: 4, title: 'Meretas Jalan Sosialisasi Literasi Media di Indonesia', img: 'https://kpi.go.id/images/banners/literasi_media_2.jpg' },
    { id: 5, title: 'Profil dan Dinamika Penyiaran di Daerah Perbatasan', img: 'https://kpi.go.id/images/banners/dinamika_penyiaran_perbatasan.jpg' },
    { id: 6, title: 'Komisi Penyiaran Indonesia Daerah: Eksistensi, Rekrutment, Tata Hubungan, Program dan Penganggaran', img: 'https://kpi.go.id/images/banners/standarisasi_program.jpg' },
    { id: 7, title: 'Buku Direktori Perizinan Penyiaran 2012', img: 'https://kpi.go.id/images/banners/Direktori_Perizinan_Penyiaran.jpg' },
    { id: 8, title: 'Laporan Rekap Perizinan Jan-Sep 2012', img: 'https://kpi.go.id/images/banners/Laporan%20Rekap%20Perizinan%20Jan-Sep%202012.jpg' },
    { id: 9, title: 'Profil KPI 2010', img: 'https://kpi.go.id/images/banners/profil_kpi_2010.jpg' },
    { id: 10, title: 'Buku Wajah Penyiaran Indonesia', img: 'https://kpi.go.id/images/2019/November/Buku-Wajah-Penyiaran.jpg' },
    { id: 11, title: 'Buku “Mengawal Demokrasi: Dinamika Pengawasan Penyiaran Pemilu 2019”', img: 'https://kpi.go.id/images/2019/Buku-Mengawal-Demokrasi.jpg' },
    { id: 12, title: 'Buku Dialektika Penyiaran Indonesia', img: 'https://kpi.go.id/images/2021/Januari/Dialetika-Penyiaran-Indonesia.jpg' },
    { id: 13, title: 'Buku TVRI dan Digitalisasi', img: 'https://kpi.go.id/images/2022/Buku-TVRI.jpg' },
    { id: 14, title: 'Buku “Antara Tantangan Zaman dan Harapan Masyarakat”', img: 'https://kpi.go.id/images/2022/Buku-Antara-Tantangan-Zaman.jpg' },
    { id: 15, title: 'Buku Gerakan Literasi Sejuta Pemirsa Tahun 2021', img: 'https://kpi.go.id/images/2022/Buku-GLSP-2021.jpg' },
    { id: 16, title: 'Buku "Potret Kualitas Siaran TV Program Berita di Indonesia"', img: 'https://kpi.go.id/images/2022/Potret-Kualitas-Program-Berita.jpg' },
    { id: 17, title: 'Buku “Potret Program Siaran Religi di TV Indonesia”', img: 'https://kpi.go.id/images/2022/Potret-Program-Siaran-Religi-di-TV.jpg' },
    { id: 18, title: 'Buku "Laporan IKPSTV 2022"', img: 'https://kpi.go.id/images/2023/Cover-Laporan-IKPSTV.jpg' },
    { id: 19, title: 'Buku "TVRI Menyatukan Bangsa"', img: 'https://kpi.go.id/images/2023/Cover-TVRI-Mempersatukan-Bangsa-4.jpg' },
    { id: 20, title: 'Buku “Potret Program Siaran Wisata dan Budaya di Indonesia”', img: 'https://kpi.go.id/images/2023/Cover-Potret-Wisata-dan-Budaya-2.jpg' },
    { id: 21, title: 'Buku "Perbincangan Bermakna di Layar Kaca"', img: 'https://kpi.go.id/images/2023/Cover-Perbincangan-Bermakna-1.jpg' },
    { id: 22, title: 'Buku "Selaksa Ide dan Kerja Nyata KPI"', img: 'https://kpi.go.id/images/2023/Cover-Selaksa-Ide-3.jpg' },
    { id: 23, title: 'Buku "Potret Kualitas Program Siaran Anak di Televisi Indonesia"', img: 'https://kpi.go.id/images/2023/Juni/Buku-Potret-Siaran-Anak.jpg' },
    { id: 24, title: 'Buku "Potret Sinetron di Televisi Indonesia"', img: 'https://kpi.go.id/images/2023/Juni/Buku-Potret-Sinetron.jpg' },
    { id: 25, title: 'Buku "Indeks Kualitas Program Siaran Televisi Periode 1 2023"', img: 'https://kpi.go.id/images/2024/Januari/Buku-Indeks-Periode-1-2023.jpg' },
    { id: 26, title: 'Buku "Indeks Kualitas Program Siaran Televisi Periode 2 2023"', img: 'https://kpi.go.id/images/2024/Maret/Buku-IKPSTV-2-2023.jpg' },
  ]